version: '3'

services:
  nginx:
    image: nginx:1.15-alpine
    depends_on: 
      - dga_intel
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - dga_intel
  certbot:
    image: certbot/certbot
    depends_on: 
      - dga_intel
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - dga_intel
  dga_intel:
    image: dga_intel
    restart: unless-stopped
    networks:
      - dga_intel
    expose:
      - "80"
networks:
  dga_intel:
